291 Imports of siblings from within a package don't get picked up in analysis. 	Search for modules in parent packages
290 Renaming package directory fials with "Could not find part of the path ..." for __init__.py
	Don?t use SuspendFileChanges if the file doesn?t exist anymore because it throws when the file doesn?t exist

288 Dragging a file into a folder causes the folder to close
	MPFProj invalidates too much when removing an item

282 Wrong parameter highlighted when passing arguments to functions
	Track parenthesis and other grouping characters independently so that we don?t include other groupings in the param index.  Add test case to CompletionContextTests

256 Renaming a file under source control reports an error
	Fix MPFProj?s renaming logic so that instead of creating a new node we update the current node in place (this matches the behavior of the C# / VB.NET project systems)

253 Changing interpreter for project doesn't rescan closed files
	We were getting the URL from the wrong child so we?d only ever scan folders/projects, not the individual Python files

258 AttributeError: '_ReplInput' object has no attribute 'readlines'
	Implement rest of file reading API

261 In REPL, "End" key goes to right edge of window, not end of line
	Add logic to the repl for the end key which matches our logic for the home key

262 Entering a comment at the prompt generates an error
	Don?t attempt to compile lines which are just comments, neither CPython nor IronPython can parse these in the interactive grammar because they expect one and only one statement.
	Opened an IronPython bug for the null ref:  http://ironpython.codeplex.com/workitem/30941

255 Modules in project don't show up in REPL import intellisense
	Merge the scopes imported into the repl w/ the analysis.
	Also when we reconnect and get the associated startup project use it?s analyzer if the interpreters match each other and do the appropriate switching of buffers to the new version

269 Incorrect error message when no interpreters are installed
	Correct the error message

264 Intellisense completions persist after resetting interpreter
	Mark the current buffers when we do a reset and don?t include them in future analysis
	Also make sure we remove buffers from our buffer parser when the screen is cleared

286 Request: ability to tell if Interactive is running
	Disable the cancel execution button if we?re not executing code

257 Sending multiple lines of input to the REPL doesn't break lines and doesn't execute multiple lines
260 Send to Interactive should send a carriage return at the end
	Split code up into multiple chunks when sending to REPL
	Use the Submit API which immediately executes a repl command


281 For, While Statements are not collapsible
	Provide regions for top-level for/while statements

296 Info tooltips show '\\u000a' instead of '\n'
	Unpickler shouldn?t use raw form for unpicking Unicode strings
	Also fix an issue w/ scraper on 3.x

Also:
	Previous fix for repl reset while running was incorrect, Python should deliver the execution completion result instead of having the repl add the prompt when resetting.
	Sys.argv should have at least one entry (an empty string) in the REPL